[project]
title = "Student Habits vs Academic Performance"
version = "0.1.0"
port = 8501
slug = "preswald-project"  
entrypoint = "hello.py"    

[branding]
name = "Preswald Project"
logo = "images/logo.png"
favicon = "images/doge.png"
primaryColor = "#F89613"

[data.student_habits_performance.csv]
type = "csv"
path = "data/student_habits_performance.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"